# Weather Data Ingestion Date Range Configuration
# This file defines the start and end dates for historical weather data ingestion

# Default date range (can be overridden via environment variables)
start_date: "2025-01-01"
end_date: "2025-06-30"

# Optional: Override with environment variables
# START_DATE_OVERRIDE: "2024-01-01"
# END_DATE_OVERRIDE: "2024-12-31"

# Date format: YYYY-MM-DD
# Examples:
# - "2024-01-01" (January 1st, 2024)
# - "2023-06-15" (June 15th, 2023)
# - "2022-12-31" (December 31st, 2022) 